### ISSUE TITLE
(In Unity Remote) Game Mechanics

### ISSUE THREAD

**Issue by HettyNurrashikin** [tjjjwxzq/50.003-Project#10]
1. Mouse auto eat the food that is nearby. Which breaks my streak :(
2. Tapping increases too much of the mouse's happiness level
3. Very difficult to get a streak because food spawned is too slow as compared to the rate the combo is changing.
4. Happiness level doesn't increase when I stroke the mouse
5. More significant change in mouse's fatness (?) Seems like mouse isn't growing much even if I try to feed a lot. (Prefer the game to be fast, but this is open to discussion)

**Comment by tjjjwxzq** [comment]
1. Agree that a streak is too hard to attain currently. Opened another issue about it. However the mouse eating things on its own, and trying to prevent it from eating things you don't want it to eat, as it grows bigger and bigger, should be one of the challenges of the game, I feel
2. Opened a separate issue about this
3. See 1.
4. Need to fix the swipe detection. See 2.
5. Maybe more visual feedback when the mouse levels up (animation?)
