### ISSUE TITLE
(APK version) UI issues

### ISSUE THREAD

**Issue by HettyNurrashikin** [tjjjwxzq/50.003-Project#9]
1. To include some kind of streaks counter on the game screen so that players will know how many more streaks to go before reaching the frenzy mode
2. Combo, spawned food and the happiness bar is too small

**Comment by tjjjwxzq** [comment]
1. Will depend on how we decide to modify the streak counting: ie. to make entering frenzy mode easier, either reduce the streak count or don't make it based on streak, but enter frenzy mode once every N combos are attained (that is, one does not need to continuously combo in between)
2. Fixed the UI issues by making sure the canvas scaler component was set to scale with screen size
